export const sharedStyles: Record<string, any> = {
  page: {
    minHeight: "100vh",
    backgroundColor: "#f3f4f6",
    paddingTop: "80px",
    fontFamily: "sans-serif",
  },
  container: {
    maxWidth: "600px",
    margin: "0 auto",
    padding: "24px",
    background: "#fff",
    borderRadius: "8px",
    boxShadow: "0 0 12px rgba(0,0,0,0.1)",
  },
  title: {
    fontSize: "24px",
    marginBottom: "24px",
    textAlign: "center" as const,
    color: "#1f2937",
  },
  label: {
    display: "block",
    marginBottom: "6px",
    fontWeight: "bold",
    color: "#374151",
    marginTop: "16px",
  },
  input: {
    width: "100%",
    padding: "10px",
    fontSize: "16px",
    borderRadius: "4px",
    border: "1px solid #d1d5db",
    background: "#fff",
    boxSizing: "border-box" as const,
  },
  error: {
    color: "red",
    fontSize: "14px",
    marginTop: "4px",
  },
  buttonGroup: {
    display: "flex",
    gap: "12px",
    justifyContent: "flex-end",
    marginTop: "24px",
    flexWrap: "wrap",
  },
  primaryButton: {
    background: "#2563eb",
    color: "white",
    padding: "10px 16px",
    fontSize: "16px",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
  },
  secondaryButton: {
    background: "#e5e7eb",
    color: "#1f2937",
    padding: "10px 16px",
    fontSize: "16px",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
  },
  dangerButton: {
    background: "#dc2626",
    color: "white",
    padding: "10px 16px",
    fontSize: "16px",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
  },
};
